# Worlds where XP boosts wont be given even if the player has permission
disabled-worlds:
  - lobby
  - mining

# Requires permission 'qxpboosts.player' in order to receive an active boost
requires-permission: true
