name: qXP-Boosts
version: '${project.version}'
main: gg.quartzdev.qxpboosts.qXpBoosts
api-version: '1.19'
dependencies:
  - name: PlaceholderAPI
    required: false
    bootstrap: false
#  server:
#    PlaceholderAPI:
#      load: BEFORE
#      required: false